### PR TITLE
Upload files in threads

### PR DESCRIPTION
**Pull request by psrpinto**
This PR implements file uploads in threads. Previously, files uploaded in a thread on Slack, would render on the main timeline on Matrix. With this PR, the files is correctly uploaded to the Matrix thread.

The upstream issue is: https://github.com/matrix-org/matrix-appservice-slack/issues/671

----
This PR is the culmination of refactoring the Slack message parsing logic into a `SlackMessageParser` which exposes a single method:

```typescript
import {ISlackMessageEvent} from "./BaseSlackHandler";
import {MessageEventContent} from "matrix-bot-sdk";

async parse(message: ISlackMessageEvent): Promise<MessageEventContent[]>;
```

Since one Slack message might result in multiple Matrix events (each file referenced by the message is a separate event on Matrix), the `parse()` method returns an array of Matrix events. The array might be empty if the parser failed to parse the message.

For matrix events that are files, the parser does not upload them to Matrix. Instead, it sets the Slack URL to the file in the Matrix event, with an appended access token:

```json
{
    "body": "foo.png",
    "info": {
      "mimetype": "image/png",
      "size": 97335,
      "w": 715,
      "h": 715,
      "thumbnail_url": "https://files.slack.com/...?token=abc123",
      "thumbnail_info": {
        "w": 360,
        "h": 360
      }
    },
    "msgtype": "m.image",
    "url": "https://files.slack.com/...?token=abc123"
}
```

Consumers of the parser then need to actually upload the file, and replace the URL in the Matrix event.

### CODE REVIEW

**Comment by akirk** [comment]
Could you for now include (code) comments of which functionality should be actually in https://github.com/matrix-org/matrix-appservice-bridge/

We also discussed to update the README.md with the differences to upstream but this can be done in an upcoming PR.

**Comment by psrpinto** [comment]
> Could you for now include (code) comments of which functionality should be actually in matrix-appservice-bridge.
> We also discussed to update the README.md with the differences to upstream but this can be done in an upcoming PR.

@akirk, since the topic of which logic should be in matrix-appservice-bridge is a more generic one (not just relating to files), I will address it together with the other topic of documenting differences between this fork and the upstream bridge, in a separate PR.

**Comment by akirk** [comment]
Sounds good to me, I just thought it would be good to note it down whenever you encounter it, not restricted to this PR.

**Comment by psrpinto** [comment]
I tested quite a bit locally, merging.

**Pull request merged**
